name: expensetrack
description: An app to track your expenses
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  material_design_icons_flutter: ^6.0.7096
  shared:
    path: ../server/packages/shared
  dio: ^5.1.1
  logger: ^1.3.0
  firebase_crashlytics: ^3.2.0
  firebase_core: ^2.11.0
  intl: any
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.0
  fl_chart: ^0.62.0
  sliver_tools: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.1


flutter:
  uses-material-design: true

  assets:
    - assets/