name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.5.8
  json_serializable: ^6.6.2
  lints: ^5.1.1
  test: ^1.21.0
