definitions:
  models.Transaction:
    properties:
      account:
        type: string
      amount:
        type: number
      category:
        items:
          type: string
        type: array
      date:
        type: string
      description:
        maxLength: 255
        type: string
      id:
        type: integer
      text:
        type: string
      verification_number:
        type: string
    required:
    - date
    - description
    type: object
info:
  contact: {}
  title: Expenses Tracker API
  version: "0.1"
paths:
  /transactions:
    get:
      description: Get a list of all transactions
      parameters:
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Number of results to return
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
swagger: "2.0"
