definitions:
  models.Category:
    properties:
      description:
        maxLength: 255
        type: string
      id:
        type: integer
      name:
        maxLength: 45
        type: string
    required:
    - name
    type: object
  models.Transaction:
    properties:
      account:
        maxLength: 20
        type: string
      amount:
        type: number
      categories:
        items:
          type: integer
        type: array
      date:
        type: string
      description:
        maxLength: 255
        type: string
      id:
        type: integer
      text:
        maxLength: 45
        type: string
      verification_number:
        maxLength: 20
        type: string
    required:
    - account
    - date
    - text
    type: object
info:
  contact: {}
  title: Expenses Tracker API
  version: "0.1"
paths:
  /categories:
    get:
      description: Get a list of all categories
      parameters:
      - description: Category IDs to filter by
        in: query
        name: id[]
        type: array
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
  /transactions:
    get:
      description: Get a list of all transactions
      parameters:
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Number of results to return, defaults to 10
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
    post:
      description: Add a new transaction
      parameters:
      - description: The transaction to add
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transaction'
swagger: "2.0"
