name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  dotenv: ^4.1.0
  freezed_annotation: ^2.2.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  postgres: ^2.6.1
  shared:
    path: packages/shared

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

assets:
  - .env
