consumes:
- application/json
info:
  description: Backend API for expenses tracker
  title: Expenses Tracker API
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  transaction:
    type: object
    required:
      - date
      - account
      - text
      - amount
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      date:
        type: string
        format: date-time
      account:
        type: string
        maxLength: 20
      verification_number:
        type: string
        maxLength: 20
      text:
        type: string
        maxLength: 45
      description:
        type: string
        maxLength: 255
      amount:
        type: number
paths: 
  /transactions:
    get:
      summary: Get a list of transactions
      parameters:
        - name: offset
          in: query
          type: integer
          format: int64
          default: 0
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/transaction"
        default:
          description: Misc error response
          schema:
            $ref: "#/definitions/error"

