// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAssF54Zo1GqGe6oyKDxf-g2wcnCfKQnkQ',
    appId: '1:677224566709:web:4d2c02f8bb4386366253fc',
    messagingSenderId: '677224566709',
    projectId: 'expenses-tracker-8ef0a',
    authDomain: 'expenses-tracker-8ef0a.firebaseapp.com',
    storageBucket: 'expenses-tracker-8ef0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqCU5J_rJLpKCbBYzmkyz__0oMD0vCsI',
    appId: '1:677224566709:android:0468829dbf2d91fc6253fc',
    messagingSenderId: '677224566709',
    projectId: 'expenses-tracker-8ef0a',
    storageBucket: 'expenses-tracker-8ef0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJjVQLC6rYpMsF6Chy1rJYqqc5UXPi1E',
    appId: '1:677224566709:ios:c579b7d2fd01b77a6253fc',
    messagingSenderId: '677224566709',
    projectId: 'expenses-tracker-8ef0a',
    storageBucket: 'expenses-tracker-8ef0a.appspot.com',
    androidClientId: '677224566709-c5n22iateh887s481vsopli035qgr1v0.apps.googleusercontent.com',
    iosClientId: '677224566709-b89j27nfju5el7hvf9qbhravq48c5iri.apps.googleusercontent.com',
    iosBundleId: 'se.hultergard.expensetrack',
  );
}
